/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/battery-pack.glb -o src/components/batteryPack.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../assets/Customization";
import { Color } from "three";

const BatteryPack = (props) => {
    const { nodes, materials } = useGLTF("./models/battery-pack.glb");
    const { helmetColor } = useCustomization();

    nodes.Helmet_Assembly012.material.color = new Color(helmetColor.color);

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Helmet_Assembly012.geometry}
                material={nodes.Helmet_Assembly012.material}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
};

useGLTF.preload("./models/battery-pack.glb");

export default BatteryPack;
