/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/helmet.glb 
*/

import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../contexts/Customization";
import { Color } from "three";

const Helmet = (props) => {
    const { nodes, materials } = useGLTF("./models/helmet.glb");
    const { helmetColor } = useCustomization();

    nodes.Helmet_Assembly001.material.color = new Color(helmetColor.color);

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Helmet_Assembly001.geometry}
                material={nodes.Helmet_Assembly001.material}
                rotation={[Math.PI / 2, 0, 0]}
            ></mesh>
        </group>
    );
};

useGLTF.preload("./models/helmet.glb");

export default Helmet;
