/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/light.glb -o src/components/Light.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../contexts/Customization";
import { Color } from "three";

const Light = (props) => {
    const { nodes, materials } = useGLTF("./models/light.glb");
    const { helmetColor } = useCustomization();

    nodes.Helmet_Assembly015.material.color = new Color(helmetColor.color);

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Helmet_Assembly015.geometry}
                material={nodes.Helmet_Assembly015.material}
                position={[-73.171, 29.433, 15.258]}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
};

useGLTF.preload("./models/light.glb");

export default Light;
