/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/visor.glb -o src/components/visor.jsx 
*/

import { useGLTF } from "@react-three/drei";

const Visor = (props) => {
    const { nodes, materials } = useGLTF("./models/visor.glb");

    nodes.Helmet_Assembly005.material.opacity = 0.5;
    nodes.Helmet_Assembly005.material.transparent = true;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Helmet_Assembly005.geometry}
                material={nodes.Helmet_Assembly005.material}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
};

useGLTF.preload("./models/visor.glb");

export default Visor;
