/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/yes-ear.glb -o src/components/yesEar.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../../assets/Customization";
import { Color } from "three";

const YesEar = (props) => {
    const { nodes, materials } = useGLTF("./models/yes-ear.glb");
    const { helmetColor } = useCustomization();

    nodes.Helmet_Assembly009.material.color = new Color(helmetColor.color);

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Helmet_Assembly009.geometry}
                material={nodes.Helmet_Assembly009.material}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
};

useGLTF.preload("./models/yes-ear.glb");

export default YesEar;
